GitHub/GiveCRM/src/GiveCRM.Web/Models/Donation/QuickDonateViewModel.cs
namespace GiveCRM.Web.Models.Donation
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using GiveCRM.Models;

    public class QuickDonateViewModel
    {
        public int DonorId { get; private set; }
        public IEnumerable<SelectListItem> Campaigns { get; private set; }
        public DateTime DateDonated { get; set; }
        public decimal AmountDonated { get; set; }

        public QuickDonateViewModel(int donorId, IEnumerable<Campaign> campaigns) : this(donorId, campaigns, DateTime.UtcNow) { }

        public QuickDonateViewModel(int donorId, IEnumerable<Campaign> campaigns, DateTime dateDonated, decimal amountDonated = 0m)
        {
            DonorId = donorId;
            Campaigns = campaigns.Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name });
            DateDonated = dateDonated;
            AmountDonated = amountDonated;
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Controllers/DonationController.cs
namespace GiveCRM.Web.Controllers
{
    using System;
    using System.Web.Mvc;
    using GiveCRM.BusinessLogic;
    using GiveCRM.Models;
    using GiveCRM.Web.Attributes;
    using GiveCRM.Web.Models.Donation;

    [HandleErrorWithElmah]
    public class DonationController : Controller
    {
        private readonly IDonationsService donationsService;
        private readonly ICampaignService campaignService;

        public DonationController(IDonationsService donationsService, ICampaignService campaignService)
        {
            if (donationsService == null)
            {
                throw new ArgumentNullException("donationsService");
            }

            if (campaignService == null)
            {
                throw new ArgumentNullException("campaignService");
            }
            
            this.donationsService = donationsService;
            this.campaignService = campaignService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult TopDonations()
        {
            var donations = this.donationsService.GetTopDonations(5);

            return View("DonationList", donations);
        }

        [HttpGet]
        public ActionResult LatestDonations()
        {
            var donations = this.donationsService.GetLatestDonations(5);

            return View("DonationList", donations);
        }

        [HttpGet]
        public ActionResult QuickDonate(int id)
        {
            var campaigns = this.campaignService.GetAllOpen();
            var viewModel = new QuickDonateViewModel(id, campaigns);

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult DoQuickDonate(int id, int amount, string date, int campaignId)
        {
            this.donationsService.QuickDonation(new Donation
                                                {
                                                    Amount = amount,
                                                    Date = DateTime.Parse(date),
                                                    MemberId = id,
                                                    CampaignId = campaignId
                                                });
            return View();
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Controllers/MemberController.cs
namespace GiveCRM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Routing;
    using GiveCRM.BusinessLogic;
    using GiveCRM.Models;
    using GiveCRM.Web.Attributes;
    using GiveCRM.Web.Models.Members;
    using PagedList;

    [HandleErrorWithElmah]
    public class MemberController : Controller
    {
        private const int DefaultPageSize = 25;

        private readonly IDonationsService donationsService;
        private readonly IMemberService memberService;
        private readonly ICampaignService campaignService;

        public MemberController(IDonationsService donationsService, IMemberService memberService, ICampaignService campaignService)
        {
            if (donationsService == null)
            {
                throw new ArgumentNullException("donationsService");
            }

            if (memberService == null)
            {
                throw new ArgumentNullException("memberService");
            }
            
            if (campaignService == null)
            {
                throw new ArgumentNullException("campaignService");
            }
            
            this.donationsService = donationsService;
            this.memberService = memberService;
            this.campaignService = campaignService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Title = "Add Member"; 
            return View(new MemberEditViewModel
                {
                    PhoneNumbers = new List<PhoneNumber>()
                });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Member";
            var model = this.memberService.Get(id);
            if (model.PhoneNumbers == null)
            {
                model.PhoneNumbers = new List<PhoneNumber>();
            }

            return View("Add", MemberEditViewModel.ToViewModel(model));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var member = this.memberService.Get(id);

            this.memberService.Delete(member); 

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Donate(int id)
        {
            ViewBag.MemberName = this.memberService.Get(id).ToString();

            ViewBag.Campaigns = this.campaignService.GetAllOpen().Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() });

            return View(new Donation { MemberId = id });
        }

        [HttpPost]
        public ActionResult SaveDonation(Donation donation)
        {
            this.donationsService.QuickDonation(donation);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Save(MemberEditViewModel member)
        {
            ViewBag.Title = member.Id == 0 ? "Add Member" : "Edit Member";

            if (!ModelState.IsValid)
            {
                return View("Add", member);
            }

            this.memberService.Save(member.ToModel()); 

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Search(MemberSearchViewModel model)
        {
            if (string.IsNullOrEmpty(model.SearchButton) && !model.Page.HasValue)
            {
                model.Results = CreatePagedListOfMembers(this.memberService.All(), model);
                return View(model);
            }

            var searchResults = this.memberService.Search(model.Name, model.PostCode, model.Reference);
            model.Results = CreatePagedListOfMembers(searchResults, model);

            return View(model);
        }

        private PagedMemberListViewModel CreatePagedListOfMembers(IEnumerable<Member> memberList, MemberSearchViewModel viewModel)
        {
            return new PagedMemberListViewModel(memberList.ToPagedList(viewModel.Page ?? 1, DefaultPageSize), 
                                                page => Url.Action("Index", new RouteValueDictionary
                                                                                {
                                                                                    {"Page", page},
                                                                                    {"Name", viewModel.Name},
                                                                                    {"PostCode", viewModel.PostCode},
                                                                                    {"Reference", viewModel.Reference}
                                                                                }));
        }

        [HttpGet]
        public ActionResult AjaxSearch(string criteria)
        {
            var results = this.memberService.Search(criteria);

            return View(results.Take(DefaultPageSize));
        }

        [HttpGet]
        public ActionResult TopDonors()
        {
            var members = this.memberService.All().OrderByDescending(m => m.TotalDonations).Take(5);

            return View("TopDonors", members);
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Views/Donation/DoQuickDonate.cshtml
Done!

GitHub/GiveCRM/src/GiveCRM.Web/Views/Donation/DonationList.cshtml
@using System.Globalization
@model IEnumerable<GiveCRM.Models.Donation>

@{
    Layout = null;
}

<table>
<tr>
    <th>Date</th><th>Amount</th>
</tr>

@foreach (var donation in Model)
{
    <tr>
        <td>@donation.Date.ToLongDateString()</td>
        <td>@donation.Amount.ToString("C2", NumberFormatInfo.CurrentInfo)</td>
    </tr>
}

</table>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Donation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="donations">
    <div class="row">
        <div class="span16">
<h1>Donations</h1>
        </div>
    </div>

    <div class="row">
        <div class="maincol span-two-thirds">

<h3>Top Donations</h3>

@{Html.RenderAction("TopDonations");}

<h3>Latest Donations</h3>

@{Html.RenderAction("LatestDonations");}

<h3>Top Donors</h3>

@{Html.RenderAction("TopDonors", "Member");}

        </div>

        <div class="sidebar span-one-third">
            <h2>Quick Donate</h2>
        
            @using (Html.BeginForm("AjaxSearch", "Member", FormMethod.Get, new { name = "AjaxSearch", id = "AjaxSearch" })) 
            { 
            <div class="clearfix">
                @Html.Label("SearchCriteria", "Search Criteria")
                <div class="input">
                    @Html.TextBox("SearchCriteria", null, new { @class = "span2" })
                </div>
            </div>

            <div class="actions">
                    <a class="btn primary" href="javascript:DoSearch();">Search</a>
            </div>
            }

            <div id="QuickResults">&nbsp;</div>

            <div id="AddDonation">&nbsp</div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#AjaxSearch').submit(function () { DoSearch(); return false; });
    });

    function DoSearch() {
        var criteria = $("#SearchCriteria").val();
        $('#QuickResults')[0].innerHTML = "";
        $('#AddDonation')[0].innerHTML = "";
        $.ajax({
            type: 'GET',
            url: './member/ajaxsearch?criteria=' + criteria,
            dataType: 'html',
            success: function (html, textStatus) {
                $('#QuickResults')[0].innerHTML = html;
            }
        });
    }

    function AddDonation(id) {
        $.ajax({
            type: 'GET',
            url: './donation/quickdonate?id=' + id,
            dataType: 'html',
            success: function (html, textStatus) {
                $('#AddDonation')[0].innerHTML = html;
                $('#Date').datepicker({ dateFormat: 'dd/mm/yy' });
            }
        });
    }

    function DoDonate() {
        $.ajax({
            type: 'GET',
            url: './donation/doquickdonate?id=' +
                $("#DonorId").val() +
                "&campaignId=" + $("#CampaignId").val() +
                "&amount=" + $("#Amount").val() + 
                "&date=" + $("#Date").val().replace('/', '%2F'),
            dataType: 'html',
            success: function (html, textStatus) {
                $('#AddDonation')[0].innerHTML = "Done!";
            }
        });
    }

</script>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Donation/QuickDonate.cshtml
@model GiveCRM.Web.Models.Donation.QuickDonateViewModel

<form onsubmit="DoDonate();return false;" class="form-stacked">

@Html.Hidden("DonorId", Model.DonorId)
<div class="clearfix">
    <label for="CampaignId">Campaign</label>
    <div class="input">
        @Html.DropDownList("CampaignId", Model.Campaigns)
    </div>
</div>

<div class="clearfix">
    <label for="Date">Date Donated</label>
    <div class="input">
        @Html.TextBox("Date", Model.DateDonated)
    </div>
</div>

<div class="clearfix">
    <label for="Amount">Amount</label>
    <div class="input">
        @Html.TextBox("Amount", Model.AmountDonated)
    </div>
</div>

<div class="input">
    <a class="btn small" href="javascript:DoDonate();">Save</a>
</div>

</form>
