GitHub/GiveCRM/src/GiveCRM.Web/Controllers/CampaignController.cs
namespace GiveCRM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web.Mvc;
    using GiveCRM.BusinessLogic;
    using GiveCRM.LoggingService;
    using GiveCRM.Models;
    using GiveCRM.Models.Search;
    using GiveCRM.Web.Attributes;
    using GiveCRM.Web.Infrastructure;
    using GiveCRM.Web.Models.Campaigns;
    using GiveCRM.Web.Models.Search;
    using GiveCRM.Web.Properties;

    [HandleErrorWithElmah]
    public class CampaignController : Controller
    {
        private readonly IMailingListService mailingListService;
        private readonly ISearchService searchService;
        private readonly ICampaignService campaignService;
        private readonly IMemberSearchFilterService memberSearchFilterService;
        private readonly IMemberService memberService;
        private readonly ILogService logService;
        
        public CampaignController(
            IMailingListService mailingListService, 
            ISearchService searchService, 
            ICampaignService campaignService, 
            IMemberSearchFilterService memberSearchFilterService,
            IMemberService memberService,
            ILogService logService)
        {
            this.mailingListService = mailingListService;
            this.searchService = searchService;
            this.campaignService = campaignService;
            this.memberSearchFilterService = memberSearchFilterService;
            this.memberService = memberService;
            this.logService = logService;
        }

        [HttpGet]
        public ActionResult Index(bool showClosed = false)
        {
            IEnumerable<Campaign> campaigns = showClosed ? this.campaignService.GetAllClosed() : this.campaignService.GetAllOpen();
            string title, linkText;

            if (showClosed)
            {
                title = Resources.Literal_Closed;
                linkText = Resources.Literal_Open;
            }
            else
            {
                title = Resources.Literal_Open;
                linkText = Resources.Literal_Closed;
            }

            title = string.Format("{0} {1}", title, Resources.Literal_Campaigns);
            linkText = string.Format(Resources.Show_Campaigns_Text, linkText);

            var model = new CampaignIndexViewModel(title)
                            {
                                ShowCampaignsLinkText = linkText,
                                CreateCampaignLinkText = Resources.Literal_CreateCampaign,
                                ShowClosed = showClosed,
                                Campaigns = campaigns
                            };
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new CampaignShowViewModel(Resources.Literal_CreateCampaign)
                            {
                                Campaign = new Campaign
                                               {
                                                   Name = "New Campaign"
                                               }
                            };
            return View("Show", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Campaign campaign)
        {
            var newId = this.InsertCampaign(campaign);
            return RedirectToAction("Show", new { id = newId });
        }

        private int InsertCampaign(Campaign campaign)
        {
            var savedCampaign = this.campaignService.Insert(campaign);
            return savedCampaign.Id;
        }

        [HttpGet]
        public ActionResult Show(int id)
        {
            var campaign = this.campaignService.Get(id);
            var applicableMembers = this.memberService.SearchByCampaignId(id).ToList();
            var searchFilters = this.memberSearchFilterService.ForCampaign(id)
                                    .Select(m =>
                                        {
                                            var criteriaDisplayText = SearchCriteria.Create(m.InternalName,
                                                                                            m.DisplayName,
                                                                                            (SearchFieldType) m.FilterType,
                                                                                            (SearchOperator) m.SearchOperator,
                                                                                            m.Value
                                                        ).ToFriendlyDisplayString();
                                            return new MemberSearchFilterViewModel
                                                       {
                                                                   MemberSearchFilterId = m.Id,
                                                                   CampaignId = campaign.Id,
                                                                   CriteriaDisplayText = criteriaDisplayText
                                                       };
                                        }).ToList();

            var model = new CampaignShowViewModel(Resources.Literal_ShowCampaign)
                            {
                                Campaign = campaign,
                                SearchFilters = searchFilters,
                                NoSearchFiltersText = Resources.Literal_NoSearchFiltersText,
                                NoMatchingMembersText = Resources.Literal_NoMatchingMembersText,
                                ApplicableMembers = applicableMembers,
                                IsReadonly = campaign.IsReadonly
                            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Show(CampaignShowViewModel campaignViewModel)
        {
            var campaign = campaignViewModel.Campaign;
            this.campaignService.Update(campaign);
            return RedirectToAction("Show", new { id = campaign.Id });
        }

        [HttpGet]
        public ActionResult AddMembershipSearchFilter(int campaignId)
        {
            var emptySearchCriteria = this.searchService.GetEmptySearchCriteria();
            var criteriaNames = emptySearchCriteria.Select(c => c.DisplayName);
            var searchOperators = (SearchOperator[])Enum.GetValues(typeof(SearchOperator));

            var model = new AddSearchFilterViewModel(Resources.Literal_AddSearchFilter)
                            {
                                CampaignId = campaignId,
                                CriteriaNames = criteriaNames.Select(s => new SelectListItem { Value = s, Text = s }),
                                SearchOperators = searchOperators.Select(o => new SelectListItem { Value = o.ToString(), Text = o.ToFriendlyDisplayString() })
                            };
            return View("AddSearchFilter", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMembershipSearchFilter(AddSearchFilterViewModel viewModel)
        {
            var searchCriteria = this.searchService.GetEmptySearchCriteria();

            // we have to find one
            var searchCriterion = searchCriteria.First(c => c.DisplayName == viewModel.CriteriaName);

            var memberSearchFilter = new MemberSearchFilter
                                             {
                                                 CampaignId = viewModel.CampaignId,
                                                 InternalName = searchCriterion.InternalName,
                                                 FilterType = (int)searchCriterion.Type,
                                                 DisplayName = viewModel.CriteriaName,
                                                 SearchOperator = (int)viewModel.SearchOperator,
                                                 Value = viewModel.Value
                                             };
            this.memberSearchFilterService.Insert(memberSearchFilter);
            return RedirectToAction("Show", new { id = viewModel.CampaignId });
        }

        [HttpGet]
        public ActionResult DeleteMemberSearchFilter(int campaignId, int memberSearchFilterId)
        {
            this.memberSearchFilterService.Delete(memberSearchFilterId);
            return RedirectToAction("Show", new { id = campaignId });
        }

        [HttpGet]
        public ActionResult CloseCampaign(int campaignId)
        {
            var campaign = this.campaignService.Get(campaignId);
            var viewModel = new SimpleCampaignViewModel(Resources.Literal_CloseCampaign)
                                {
                                    CampaignId = campaignId,
                                    CampaignName = campaign.Name
                                };
            return View("Close", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CloseCampaign(SimpleCampaignViewModel viewModel)
        {
            var campaign = this.campaignService.Get(viewModel.CampaignId);
            campaign.IsClosed = "Y";
            this.campaignService.Update(campaign);
            return RedirectToAction("Index", new { showClosed = true });
        }

        [HttpGet]
        public ActionResult CommitCampaign(int campaignId)
        {
            var campaign = this.campaignService.Get(campaignId);
            var viewModel = new SimpleCampaignViewModel(Resources.Literal_CommitCampaign)
                                {

GitHub/GiveCRM/src/GiveCRM.Web/Views/Shared/Fail.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Sorry...";
}

<h2>
    Sorry...
</h2>
<p>@ViewBag.Message</p>
<p>@Html.ActionLink("Go Back", (string)ViewBag.ReturnActionName, (object)ViewBag.ReturnRouteValues)</p>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Shared/_GlobFooter.cshtml
@using GiveCRM.Web.Infrastructure
@if (ConfigurationSettings.IsUserVoiceIntegrationEnabled)
{
    <script type="text/javascript">
        var uvOptions = { };
        (function() {
            var uv = document.createElement('script');
            uv.type = 'text/javascript';
            uv.async = true;
            uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/XMFifLxGL4npm6SHybYvtw.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(uv, s);
        })();
    </script>
}

GitHub/GiveCRM/src/GiveCRM.Web/Views/Shared/_GlobHeader.cshtml
@using GiveCRM.Web.Views

<div class="fill">
	<div class="container">
		<a class="brand" href='@Url.Action("Index", "Campaign")'>
			<img src="@Url.Content("~/Content/GiveCRM-icon.png")" alt="GiveCRM" />
		</a>
          
		<ul class="nav">
			<li @Html.NavigationClassBuilder("Campaign", additionalClasses: "dropdown") data-dropdown="dropdown">
				@Html.ActionLink("Campaign", "Index", "Campaign", null, new { @class = "dropdown-toggle" })
				
				<ul class="dropdown-menu">
					<li @Html.NavigationClassBuilder("Campaign", "Index")>
						@Html.ActionLink("List Campaigns", "Index", "Campaign")
					</li>
					<li @Html.NavigationClassBuilder("Campaign", "Add")>
						@Html.ActionLink("Create Campaign", "Create", "Campaign")
					</li>
				</ul>
			</li>
			
			<li @Html.NavigationClassBuilder("Member", additionalClasses: "dropdown") data-dropdown="dropdown">
				@Html.ActionLink("Member", "Index", "Member", null, new { @class = "dropdown-toggle" })
				
				<ul class="dropdown-menu">
					<li @Html.NavigationClassBuilder("Member", "Index")>
						@Html.ActionLink("List Members", "Index", "Member")
					</li>
					<li @Html.NavigationClassBuilder("Member", "Add")>
						@Html.ActionLink("Add Members", "Add", "Member")
					</li>
				</ul>
			</li>

			<li @Html.NavigationClassBuilder("Setup", additionalClasses: "dropdown") data-dropdown="dropdown">
				@Html.ActionLink("Setup", "Index", "Setup", null, new { @class = "dropdown-toggle" })
				
				<ul class="dropdown-menu">
					<li @Html.NavigationClassBuilder("Setup", "Index")>
					        @Html.ActionLink("List Facets", "ListFacets", "Setup")
							@Html.ActionLink("Create Facet", "AddFacet", "Setup")
					</li>
				</ul>
			</li>

            <li @Html.NavigationClassBuilder("Donation")>
				@Html.ActionLink("Donations", "Index", "Donation", null, null)
			</li>
		</ul>

		<div class="pull-right">
			@if (Request.IsAuthenticated) {
				<span class="welcome">Welcome <strong>@User.Identity.Name</strong></span>
				@Html.ActionLink("Log Off", "LogOff", "Account")
			}
			else {
				<!-- TODO(BS) add submit to correct location, use validation, use Razor forms 
				<form action="?">
					<input class="input-small" type="text" name="email" placeholder="Email">
					<input class="input-small" type="password"name="password" placeholder="Password">
					<button class="btn" type="submit">Sign in</button>
				</form>

				@Html.ActionLink("Log On", "LogOn", "Account")
                -->
			 }
		</div>
	</div>
</div>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-jsa" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>@ViewBag.Title</title>
    
    <!-- TODO load bootstrap.min if we're in prod -->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")"><\/script>')</script>

    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    <script>window.jQuery.ui || document.write('<script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.min.js")"><\/script>')</script>
</head>

<body>
    <div class="page">
        <div id="header" class="topbar">
            @Html.Partial("_GlobHeader")
        </div>

        <div id="main" class="container">
            @RenderBody()
        </div>

        <div id="footer">
            @Html.Partial("_GlobFooter")
        </div>
    </div>

    <script src="@Url.Content("~/Scripts/bootstrap-dropdown.js")"></script>

    <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
        chromium.org/developers/how-tos/chrome-frame-getting-started -->
    <!--[if lt IE 7 ]>
        <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
        <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
    <![endif]-->
</body>
</html>