GitHub/GiveCRM/src/GiveCRM.Web/Models/Members/MemberEditViewModel.cs
namespace GiveCRM.Web.Models.Members
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using GiveCRM.Models;

    public class MemberEditViewModel
    {
        public MemberEditViewModel()
        {
            this.PhoneNumbers = new List<PhoneNumber>(); 
        }

        public int Id { get; set; }

        [Required] 
        [StringLength(40)] 
        public string Reference { get; set; }
        [StringLength(40)]
        public string Title { get; set; }
        [Required]
        [StringLength(100)]
        [Display(Name="First Name")]
        public string FirstName { get; set; }
        [Required]
        [StringLength(100)]
        [Display(Name="Last Name")]
        public string LastName { get; set; }
        [Required]
        [StringLength(100)]       
        public string Salutation { get; set; }
        [StringLength(100)]
        [RegularExpression("^[^\\s]+@[^\\s]+$", ErrorMessage="Enter a valid email address")] 
        [Display(Name="Email Address")]
        public string EmailAddress { get; set; }
        [StringLength(100)]
        [Display(Name="Address Line 1")]
        public string AddressLine1 { get; set; }
        [StringLength(100)]
        [Display(Name = "Address Line 2")]
        public string AddressLine2 { get; set; }
        [StringLength(100)]
        public string City { get; set; }
        [StringLength(100)]
        public string Region { get; set; }
        [StringLength(100)]
        [Display(Name = "Postal Code")]
        public string PostalCode { get; set; }
        [StringLength(100)]
        public string Country { get; set; }
        public ICollection<PhoneNumber> PhoneNumbers { get; set; }

        public Member ToModel()
        {
            return new Member
            {
                Id = this.Id, 
                Reference = this.Reference, 
                Title = this.Title, 
                FirstName = this.FirstName, 
                LastName = this.LastName,
                Salutation = this.Salutation, 
                EmailAddress = this.EmailAddress, 
                AddressLine1 = this.AddressLine1,
                AddressLine2 = this.AddressLine2, 
                City = this.City,
                Region = this.Region, 
                PostalCode = this.PostalCode,
                Country = this.Country,
                PhoneNumbers = this.PhoneNumbers
            };
        }

        public static MemberEditViewModel ToViewModel(Member member)
        {
            return new MemberEditViewModel
            {
                Id = member.Id,
                Reference = member.Reference,
                Title = member.Title,
                FirstName = member.FirstName,
                LastName = member.LastName,
                Salutation = member.Salutation,
                EmailAddress = member.EmailAddress,
                AddressLine1 = member.AddressLine1,
                AddressLine2 = member.AddressLine2,
                City = member.City,
                Region = member.Region,
                PostalCode = member.PostalCode,
                Country = member.Country,
                PhoneNumbers = member.PhoneNumbers
            }; 
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Models/Members/MemberSearchViewModel.cs
namespace GiveCRM.Web.Models.Members
{
    public class MemberSearchViewModel
    {
        public int? Page { get; set; }
        public string Name { get; set; }
        public string PostCode { get; set; }
        public string Reference { get; set; }
        public PagedMemberListViewModel Results { get; set; }
        public string SearchButton { get; set; }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Controllers/ExcelImportController.cs
namespace GiveCRM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using GiveCRM.BusinessLogic.ExcelImport;
    using GiveCRM.ImportExport;
    using GiveCRM.Web.Models;

    public class ExcelImportController : AsyncController
    {
        private const string ExcelFileExtensionOldFormat = ".xls";
        private const string ExcelFileExtensionNewFormat = ".xlsx";

        private readonly IExcelImportService excelImporter;
        
        public ExcelImportController(IExcelImportService excelImporter)
        {
            if (excelImporter == null)
            {
                throw new ArgumentNullException("excelImporter");
            }

            this.excelImporter = excelImporter;
        }

        [HttpGet]
        public ActionResult Index()
        {
           return View(new ExcelImportViewModel());
        }

        [HttpPost]
        public ActionResult ImportAsync(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return ErrorView("You did not select a file for upload.");
            }

            if (file.ContentLength <= 0)
            {
                return ErrorView("The file you uploaded was empty.");
            }

            if (!IsValidFileExtension(file.FileName))
            {
                return ErrorView("The file you uploaded does not appear to be an Excel file.");
            }

            // Process the file
            Task.Factory.StartNew(() => ImportAsync(file.FileName, file.InputStream));
            return RedirectToAction("Index", "Member");
        }

        [HttpGet]
        public ActionResult ImportCompleted(IEnumerable<IDictionary<string, object>> data)
        {
            return RedirectToAction("Index", "Member");
        }

        private ActionResult ErrorView(string message)
        {
            ViewBag.Error = message;
            return View("Index", new ExcelImportViewModel());
        }

        private bool IsValidFileExtension(string fileName)
        {
            return IsOldExcelFormat(fileName) || IsNewExcelFormat(fileName);
        }

        private static bool IsOldExcelFormat(string fileName)
        {
            return fileName.EndsWith(ExcelFileExtensionOldFormat);
        }

        private static bool IsNewExcelFormat(string fileName)
        {
            return fileName.EndsWith(ExcelFileExtensionNewFormat);
        }

        private void ImportAsync(string fileName, Stream fileStream)
        {
            AsyncManager.OutstandingOperations.Increment();

            this.excelImporter.ImportCompleted += (s, e) =>
            {
                AsyncManager.Parameters["members"] = e.ImportedData;
                AsyncManager.OutstandingOperations.Decrement();
            };

            this.excelImporter.ImportFailed += (s, e) =>
            {
                AsyncManager.Parameters["exception"] = e.Exception;
                AsyncManager.OutstandingOperations.Decrement();
            };

            var fileType = IsNewExcelFormat(fileName) ? ExcelFileType.XLSX : ExcelFileType.XLS;
            this.excelImporter.Import(fileType, fileStream);
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Controllers/MemberController.cs
namespace GiveCRM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Routing;
    using GiveCRM.BusinessLogic;
    using GiveCRM.Models;
    using GiveCRM.Web.Attributes;
    using GiveCRM.Web.Models.Members;
    using PagedList;

    [HandleErrorWithElmah]
    public class MemberController : Controller
    {
        private const int DefaultPageSize = 25;

        private readonly IDonationsService donationsService;
        private readonly IMemberService memberService;
        private readonly ICampaignService campaignService;

        public MemberController(IDonationsService donationsService, IMemberService memberService, ICampaignService campaignService)
        {
            if (donationsService == null)
            {
                throw new ArgumentNullException("donationsService");
            }

            if (memberService == null)
            {
                throw new ArgumentNullException("memberService");
            }
            
            if (campaignService == null)
            {
                throw new ArgumentNullException("campaignService");
            }
            
            this.donationsService = donationsService;
            this.memberService = memberService;
            this.campaignService = campaignService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Title = "Add Member"; 
            return View(new MemberEditViewModel
                {
                    PhoneNumbers = new List<PhoneNumber>()
                });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Member";
            var model = this.memberService.Get(id);
            if (model.PhoneNumbers == null)
            {
                model.PhoneNumbers = new List<PhoneNumber>();
            }

            return View("Add", MemberEditViewModel.ToViewModel(model));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var member = this.memberService.Get(id);

            this.memberService.Delete(member); 

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Donate(int id)
        {
            ViewBag.MemberName = this.memberService.Get(id).ToString();

            ViewBag.Campaigns = this.campaignService.GetAllOpen().Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() });

            return View(new Donation { MemberId = id });
        }

        [HttpPost]
        public ActionResult SaveDonation(Donation donation)
        {
            this.donationsService.QuickDonation(donation);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Save(MemberEditViewModel member)
        {
            ViewBag.Title = member.Id == 0 ? "Add Member" : "Edit Member";

            if (!ModelState.IsValid)
            {
                return View("Add", member);
            }

            this.memberService.Save(member.ToModel()); 

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Search(MemberSearchViewModel model)
        {
            if (string.IsNullOrEmpty(model.SearchButton) && !model.Page.HasValue)
            {
                model.Results = CreatePagedListOfMembers(this.memberService.All(), model);
                return View(model);
            }

            var searchResults = this.memberService.Search(model.Name, model.PostCode, model.Reference);
            model.Results = CreatePagedListOfMembers(searchResults, model);

            return View(model);
        }

        private PagedMemberListViewModel CreatePagedListOfMembers(IEnumerable<Member> memberList, MemberSearchViewModel viewModel)
        {
            return new PagedMemberListViewModel(memberList.ToPagedList(viewModel.Page ?? 1, DefaultPageSize), 
                                                page => Url.Action("Index", new RouteValueDictionary
                                                                                {
                                                                                    {"Page", page},
                                                                                    {"Name", viewModel.Name},
                                                                                    {"PostCode", viewModel.PostCode},
                                                                                    {"Reference", viewModel.Reference}
                                                                                }));
        }

        [HttpGet]
        public ActionResult AjaxSearch(string criteria)
        {
            var results = this.memberService.Search(criteria);

            return View(results.Take(DefaultPageSize));
        }

        [HttpGet]
        public ActionResult TopDonors()
        {
            var members = this.memberService.All().OrderByDescending(m => m.TotalDonations).Take(5);

            return View("TopDonors", members);
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/Add.cshtml
@model GiveCRM.Web.Models.Members.MemberEditViewModel 

<h2>@ViewBag.Title</h2>

@Html.ValidationSummary("", new { @class = "alert-message warning" })

<div>
@{Html.BeginForm("Save", "Member", FormMethod.Post, new { id = "addMember" });}

@Html.HiddenFor(m => m.Id)

@EditHelper.FieldWithValidation(Html, m => m.Reference)
@EditHelper.FieldWithValidation(Html, m => m.Title)
@EditHelper.FieldWithValidation(Html, m => m.Salutation)
@EditHelper.FieldWithValidation(Html, m => m.FirstName)
@EditHelper.FieldWithValidation(Html, m => m.LastName)
@EditHelper.FieldWithValidation(Html, m => m.AddressLine1)
@EditHelper.FieldWithValidation(Html, m => m.AddressLine2)
@EditHelper.FieldWithValidation(Html, m => m.City)
@EditHelper.FieldWithValidation(Html, m => m.PostalCode)
@EditHelper.FieldWithValidation(Html, m => m.Region)
@EditHelper.FieldWithValidation(Html, m => m.Country)
@EditHelper.FieldWithValidation(Html, m => m.EmailAddress)

<div id="PhoneNumbers">
@{
    int i = 0;
    foreach (var phone in Model.PhoneNumbers)
    {
        <div class="editor-label"><label for="PhoneNumbers[@i].Number">@phone.PhoneNumberType</label></div>
        <div class="editor-field"><input id="PhoneNumbers[@i].Number" name="PhoneNumbers[@i].Number" type="text" value="@phone.Number" /></div>
        <input type="hidden" name="PhoneNumbers[@i].MemberId" value="@phone.MemberId" />
        <input type="hidden" name="PhoneNumbers[@i].Id" value="@phone.Id" />
        <input type="hidden" class="numbertype" name="PhoneNumbers[@i].PhoneNumberType" value="@phone.PhoneNumberType" />
        i++;
    }
}
</div>

<div id="AddNumber">
    <div class="editor-label"><label for="AddNumber_Type">Number Type</label></div>
    <div class="editor-field"><select id="AddNumber_Type" name="AddNumber_Type">
    @foreach (int phoneType in Enum.GetValues(typeof(GiveCRM.Models.PhoneNumberType)))
    {
       <option value="@phoneType">@Enum.GetName(typeof(GiveCRM.Models.PhoneNumberType), @phoneType)</option>
    }
    </select></div>
    <div class="editor-label"><label for="AddNumber_Number">Number</label></div> 
    <div class="editor-field">
        <input id="AddNumber_Number" name="number" type="text" />
        <input id="AddNumber_Button" type="button" value="Add Number" />
    </div>
</div>

<input type="submit" value="Save" />
@{Html.EndForm();}

<div>

<script type="text/javascript">

    $(function () {
        $('#AddNumber_Button').click(function () {
            var index = $('.numbertype').length;
            var type = htmlEncode($('#AddNumber_Type option:selected').text());
            var number = htmlEncode($('#AddNumber_Number').val());
            $('#AddNumber_Number').val('');
            if (number.trim() === '') {
                return;
            }               
            
            $('#PhoneNumbers').append(
                '<label for="PhoneNumbers[' + index + '].Number">' + type +
                '</label><input name="PhoneNumbers[' + index + '].Number" type="text" value="' + number + '" /><br />' +
                '<input type="hidden" name="PhoneNumbers[' + index + '].Id" value="0" />' +
                '<input type="hidden" class="numbertype" name="PhoneNumbers[' + index + '].PhoneNumberType" value="' + type + '" />');
        });

        var htmlEncode = function (val) {
            return $('<div/>').text(val).html();
        };
    }); 
</script>
</div>
</div>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/AjaxSearch.cshtml
@model IEnumerable<GiveCRM.Models.Member>
@{
    Layout = null;
}
@foreach (var member in Model)
{
    <p style="margin:0; padding:0;"><a href="javascript:AddDonation(@member.Id);">@member.FirstName @member.LastName @member.PostalCode</a></p>
}

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/Donate.cshtml
@model GiveCRM.Models.Donation

@{
    ViewBag.Title = "Donate";
}
<h2>Add Donation for @ViewBag.MemberName</h2>

@{Html.BeginForm(actionName: "SaveDonation", controllerName: "Member");}

@Html.HiddenFor(d => d.MemberId)
@EditHelper.DropdownFor(Html, d => d.CampaignId, (IEnumerable<SelectListItem>)ViewBag.Campaigns)
@EditHelper.Field(Html, d=> d.Date)
@EditHelper.Field(Html, d => d.Amount)
<input type="submit" value="Save" />
@{Html.EndForm();}

<script type="text/javascript" language="javascript">
    $(function () {
        $("#Date").datepicker({ dateFormat: 'dd/mm/yy' });
    });
</script>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Members Dashboard</h2>

<div id="actions">
    <ul>
        <li>@Html.ActionLink("Add New Member", "Add")</li>
        <li>@Html.ActionLink("Import Excel Spreadsheet", "Index", "ExcelImport")</li>
    </ul>
</div>

<div id="search">
    @{ Html.RenderAction("Search"); }
</div>

<div id="results">&nbsp;</div>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/MembersList.cshtml
@using PagedList.Mvc
@model GiveCRM.Web.Models.Members.PagedMemberListViewModel
@{
    Layout = null;
}

<script src="@Url.Content("~/Scripts/ViewScripts/MemberList.js")" type="text/javascript"></script>
<script type="text/javascript">

    $(function () {
        MemberList.Initialise();
    });

</script>

@if (Model != null && Model.Count > 0)
{
<table>
    @{ Html.RenderPartial("_TableOfMembers", Model); }

    <tr>
        <td colspan="7" style="text-align: center">
            <style type="text/css">
              .PagedList-pager ul li
              {
                  display: inline;
                  margin: 0 5px;
              }
          
              .PagedList-currentPage { font-weight: bold; }
              .PagedList-currentPage a { color: Black; }
            </style>
            @Html.PagedListPager(Model, Model.PagingFunction, PagedListRenderOptions.OnlyShowFivePagesAtATime)
        </td>
    </tr>
</table>
}
else
{
    <p>Your search returned no results.</p>
}

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/Search.cshtml
@model GiveCRM.Web.Models.Members.MemberSearchViewModel

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@using (Html.BeginForm(actionName: "Search", controllerName: "Member", method: FormMethod.Get))
{
    @EditHelper.Field(Html, model => model.Name)
    @EditHelper.Field(Html, model => model.PostCode)
    @EditHelper.Field(Html, model => model.Reference)
        
    <input type="submit" value="Search" name="SearchButton" />
}

@{ Html.RenderPartial("MembersList", Model.Results, new ViewDataDictionary()); }

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/TopDonors.cshtml
@model IEnumerable<GiveCRM.Models.Member>

<table>
@{Html.RenderPartial("_TableOfMembers", Model);}
</table>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Member/_TableOfMembers.cshtml
@model IEnumerable<GiveCRM.Models.Member>

<tr>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>Reference</th>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
</tr>

@foreach (var member in Model)
{
    <tr>
        <td>@Html.ActionLink("Edit", "Edit", new { id = member.Id })</td>
        <td>@Html.ActionLink("Delete", "Delete", new { id = member.Id })</td>
        <td class="wideEnough">@Html.ActionLink("Log Donation", "Donate", new { id = member.Id })</td>
        <td>@member.Reference</td>
        <td>@member.Salutation @member.FirstName @member.LastName</td>
        <td>@member.AddressLine1 @member.AddressLine2 <br />@member.City @member.PostalCode</td>
        <td><a href="mailto:@member.EmailAddress">@member.EmailAddress</a></td>
    </tr>
}