GitHub/GiveCRM/src/GiveCRM.Web/Controllers/SetupController.cs
namespace GiveCRM.Web.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using GiveCRM.BusinessLogic;
    using GiveCRM.Models;
    using GiveCRM.Web.Attributes;
    using GiveCRM.Web.Models.Facets;

    [HandleErrorWithElmah]
    public class SetupController : Controller
    {
        private readonly IFacetsService facetService;

        public SetupController(IFacetsService facetsService)
        {
            this.facetService = facetsService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddFacet()
        {
            var facet = new Facet
                {
                    Values = new List<FacetValue>()
                };
            return View("EditFacet", facet);
        }

        [HttpGet]
        public ActionResult EditFacet(int id)
        {
            var facet = this.facetService.Get(id);
            return View("EditFacet", facet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveFacet(Facet facet)
        {
            if (facet.Id > 0)
            {
                this.facetService.Update(facet);
            }
            else
            {
                this.facetService.Insert(facet);            
            }

            return RedirectToAction("ListFacets");
        }

        [HttpGet]
        public ActionResult ListFacets()
        {
            var facets = new List<Facet>(this.facetService.All());
            var viewModel = new FacetListViewModel
            {
                Facets = facets
            };

            return View(viewModel);
        }
    }
}

GitHub/GiveCRM/src/GiveCRM.Web/Views/Setup/EditFacet.cshtml
@model GiveCRM.Models.Facet

@{
    var pageTitle = Model.Id > 0 ? "Edit facet" : "Create Facet";
    ViewBag.Title = pageTitle;
}
<script src="@Url.Content("~/Scripts/ViewScripts/EditFacet.js")" type="text/javascript"></script>
<script type="text/javascript">

    $(function () {
        EditFacet.Initialise();
    });

</script>
<h2>@pageTitle</h2>
<div>
@{Html.BeginForm("SaveFacet", "Setup", FormMethod.Post);}
@Html.AntiForgeryToken()
@Html.HiddenFor(f => f.Id)
@Html.TextBoxFor(f => f.Name)

@Html.DropDownListFor(f => f.Type, 
    new List<SelectListItem>
        {
            new SelectListItem { Text = "Free Text", Value="FreeText" }, 
            new SelectListItem { Text = "Lookup", Value="List" }
        })

    <div id="FacetOptions">
        @{
            int i = 0;
            foreach (var option in Model.Values)
            {
                <div class="input">
                <input id="Values[@i].ValueBox" name="Values[@i].Value" type="text" value="@option.Value" />
                <input type="hidden" name="Values[@i].Id" value="@option.Id" />
                <input type="hidden" name="Values[@i].FacetId" class="facetCount" value="@option.FacetId" />
                </div>
                <br />
                i++;
            }
        }
    </div>

    <div id="ddOption" class="input">
        <input id="AddValue_Value" name="value" type="text" />
        <input id="AddValue_Button" type="button" value="Add Value" /><br />
    </div>

<div style="clear:both;margin:4px;">
<input type="submit" value="Save" />
</div>

@{Html.EndForm();}
</div>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Setup/Index.cshtml
@{
    ViewBag.Title = "GiveCRM Setup";
}

<h2>Setup</h2>

GitHub/GiveCRM/src/GiveCRM.Web/Views/Setup/ListFacets.cshtml
@model GiveCRM.Web.Models.Facets.FacetListViewModel
           
@{
    ViewBag.Title = "Show Facets";
}

<h2>List Facets</h2>

@if (Model.Facets.Count == 0)
{
    <div>No facets are defined</div> 
}
<ul>
@foreach (var facet in Model.Facets)
{
    <li><strong>@facet.Name</strong> (@facet.Type) 
    @Html.ActionLink("Edit", "EditFacet", new { id = facet.Id }) </li>
    if ((facet.Values != null) && (facet.Values.Count > 0))
     {
        <div>Values:
        <ul>
         @foreach(var facetValue in facet.Values)
         {
             <li>@facetValue.Value</li>
         }
        </ul>
        </div>
     }
}
</ul>

@Html.ActionLink("Create facet", "AddFacet")